package com.bsite.vo.variant;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class ProbeVO implements Serializable {
//	//http://mutation-marker-example-5000.themoagen.com/cgi-bin/edesign2/results.cgi/
	@JsonProperty("SEQUENCE_TEMPLATE")
	private String SEQUENCE_TEMPLATE;
	@JsonProperty("Upload")
	private String Upload;
	@JsonProperty("PRIMER_MISPRIMING_LIBRARY")
	private String PRIMER_MISPRIMING_LIBRARY;
	@JsonProperty("Design")
	private String Design;
	@JsonProperty("MUST_XLATE_PRIMER_PICK_LEFT_PRIMER")
	private String MUST_XLATE_PRIMER_PICK_LEFT_PRIMER;
	@JsonProperty("SEQUENCE_PRIMER")
	private String SEQUENCE_PRIMER;
	@JsonProperty("MUST_XLATE_PRIMER_PICK_RIGHT_PRIMER")
	private String MUST_XLATE_PRIMER_PICK_RIGHT_PRIMER;
	@JsonProperty("SEQUENCE_PRIMER_REVCOMP")
	private String SEQUENCE_PRIMER_REVCOMP;
	@JsonProperty("MUST_XLATE_PRIMER_PICK_INTERNAL_OLIGO")
	private String MUST_XLATE_PRIMER_PICK_INTERNAL_OLIGO;
	@JsonProperty("PRIMER_INTERNAL_OLIGO_DIRECTION")
	private String PRIMER_INTERNAL_OLIGO_DIRECTION;
	@JsonProperty("MUST_XLATE_PRIMER_INTERNAL_MODIFY_OLIGO")
	private String MUST_XLATE_PRIMER_INTERNAL_MODIFY_OLIGO;
	@JsonProperty("SEQUENCE_INTERNAL_OLIGO")
	private String SEQUENCE_INTERNAL_OLIGO;
	@JsonProperty("PRIMER_NUM_RETURN")
	private String PRIMER_NUM_RETURN;
	@JsonProperty("SEQUENCE_ID")
	private String SEQUENCE_ID;
	@JsonProperty("SEQUENCE_TARGET")
	private String SEQUENCE_TARGET;
	@JsonProperty("SEQUENCE_OVERLAP_JUNCTION_LIST")
	private String SEQUENCE_OVERLAP_JUNCTION_LIST;
	@JsonProperty("SEQUENCE_EXCLUDED_REGION")
	private String SEQUENCE_EXCLUDED_REGION;
	@JsonProperty("SEQUENCE_PRIMER_PAIR_OK_REGION_LIST")
	private String SEQUENCE_PRIMER_PAIR_OK_REGION_LIST;
	@JsonProperty("SEQUENCE_INCLUDED_REGION")
	private String SEQUENCE_INCLUDED_REGION;
	@JsonProperty("SEQUENCE_INTERNAL_EXCLUDED_REGION")
	private String SEQUENCE_INTERNAL_EXCLUDED_REGION;
	@JsonProperty("SEQUENCE_FORCE_LEFT_START")
	private String SEQUENCE_FORCE_LEFT_START;
	@JsonProperty("SEQUENCE_FORCE_LEFT_END")
	private String SEQUENCE_FORCE_LEFT_END;
	@JsonProperty("SEQUENCE_FORCE_RIGHT_END")
	private String SEQUENCE_FORCE_RIGHT_END;
	@JsonProperty("SEQUENCE_FORCE_RIGHT_START")
	private String SEQUENCE_FORCE_RIGHT_START;
	@JsonProperty("PRIMER_MIN_SIZE")
	private String PRIMER_MIN_SIZE;
	@JsonProperty("PRIMER_OPT_SIZE")
	private String PRIMER_OPT_SIZE;
	@JsonProperty("PRIMER_MAX_SIZE")
	private String PRIMER_MAX_SIZE;
	@JsonProperty("PRIMER_MIN_TM")
	private String PRIMER_MIN_TM;
	@JsonProperty("PRIMER_OPT_TM")
	private String PRIMER_OPT_TM;
	@JsonProperty("PRIMER_MAX_TM")
	private String PRIMER_MAX_TM;
	@JsonProperty("PRIMER_PAIR_MAX_DIFF_TM")
	private String PRIMER_PAIR_MAX_DIFF_TM;
	@JsonProperty("PRIMER_PRODUCT_MIN_TM")
	private String PRIMER_PRODUCT_MIN_TM;
	@JsonProperty("PRIMER_PRODUCT_OPT_TM")
	private String PRIMER_PRODUCT_OPT_TM;
	@JsonProperty("PRIMER_PRODUCT_MAX_TM")
	private String PRIMER_PRODUCT_MAX_TM;
	@JsonProperty("PRIMER_MIN_GC")
	private String PRIMER_MIN_GC;
	@JsonProperty("PRIMER_OPT_GC_PERCENT")
	private String PRIMER_OPT_GC_PERCENT;
	@JsonProperty("PRIMER_MAX_GC")
	private String PRIMER_MAX_GC;
	@JsonProperty("PRIMER_PRODUCT_SIZE_RANGE")
	private String PRIMER_PRODUCT_SIZE_RANGE;
	@JsonProperty("PRIMER_MAX_END_STABILITY")
	private String PRIMER_MAX_END_STABILITY;
	@JsonProperty("PRIMER_MAX_LIBRARY_MISPRIMING")
	private String PRIMER_MAX_LIBRARY_MISPRIMING;
	@JsonProperty("PRIMER_PAIR_MAX_LIBRARY_MISPRIMING")
	private String PRIMER_PAIR_MAX_LIBRARY_MISPRIMING;
	@JsonProperty("PRIMER_MAX_TEMPLATE_MISPRIMING_TH")
	private String PRIMER_MAX_TEMPLATE_MISPRIMING_TH;
	@JsonProperty("PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING_TH")
	private String PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING_TH;
	@JsonProperty("PRIMER_MAX_SELF_ANY_TH")
	private String PRIMER_MAX_SELF_ANY_TH;
	@JsonProperty("PRIMER_MAX_SELF_END_TH")
	private String PRIMER_MAX_SELF_END_TH;
	@JsonProperty("PRIMER_PAIR_MAX_COMPL_ANY_TH")
	private String PRIMER_PAIR_MAX_COMPL_ANY_TH;
	@JsonProperty("PRIMER_PAIR_MAX_COMPL_END_TH")
	private String PRIMER_PAIR_MAX_COMPL_END_TH;
	@JsonProperty("PRIMER_MAX_TEMPLATE_MISPRIMING")
	private String PRIMER_MAX_TEMPLATE_MISPRIMING;
	@JsonProperty("PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING")
	private String PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING;
	@JsonProperty("PRIMER_MAX_SELF_ANY")
	private String PRIMER_MAX_SELF_ANY;
	@JsonProperty("PRIMER_MAX_SELF_END")
	private String PRIMER_MAX_SELF_END;
	@JsonProperty("PRIMER_PAIR_MAX_COMPL_ANY")
	private String PRIMER_PAIR_MAX_COMPL_ANY;
	@JsonProperty("PRIMER_PAIR_MAX_COMPL_END")
	private String PRIMER_PAIR_MAX_COMPL_END;
	@JsonProperty("PRIMER_MAX_HAIRPIN_TH")
	private String PRIMER_MAX_HAIRPIN_TH;
	@JsonProperty("PRIMER_MAX_NS_ACCEPTED")
	private String PRIMER_MAX_NS_ACCEPTED;
	@JsonProperty("PRIMER_MAX_POLY_X")
	private String PRIMER_MAX_POLY_X;
	@JsonProperty("PRIMER_INSIDE_PENALTY")
	private String PRIMER_INSIDE_PENALTY;
	@JsonProperty("PRIMER_OUTSIDE_PENALTY")
	private String PRIMER_OUTSIDE_PENALTY;
	@JsonProperty("PRIMER_FIRST_BASE_INDEX")
	private String PRIMER_FIRST_BASE_INDEX;
	@JsonProperty("PRIMER_GC_CLAMP")
	private String PRIMER_GC_CLAMP;
	@JsonProperty("PRIMER_MAX_END_GC")
	private String PRIMER_MAX_END_GC;
	@JsonProperty("PRIMER_MIN_LEFT_THREE_PRIME_DISTANCE")
	private String PRIMER_MIN_LEFT_THREE_PRIME_DISTANCE;
	@JsonProperty("PRIMER_MIN_RIGHT_THREE_PRIME_DISTANCE")
	private String PRIMER_MIN_RIGHT_THREE_PRIME_DISTANCE;
	@JsonProperty("PRIMER_MIN_5_PRIME_OVERLAP_OF_JUNCTION")
	private String PRIMER_MIN_5_PRIME_OVERLAP_OF_JUNCTION;
	@JsonProperty("PRIMER_MIN_3_PRIME_OVERLAP_OF_JUNCTION")
	private String PRIMER_MIN_3_PRIME_OVERLAP_OF_JUNCTION;
	@JsonProperty("PRIMER_DNA_CONC")
	private String PRIMER_DNA_CONC;
	@JsonProperty("PRIMER_5_PRIME_TERMINAL_EXCLUDED_MOD")
	private String PRIMER_5_PRIME_TERMINAL_EXCLUDED_MOD;
	@JsonProperty("PRIMER_3_PRIME_TERMINAL_EXCLUDED_MOD")
	private String PRIMER_3_PRIME_TERMINAL_EXCLUDED_MOD;
	@JsonProperty("PRIMER_INTERNAL_MIN_SIZE")
	private String PRIMER_INTERNAL_MIN_SIZE;
	@JsonProperty("PRIMER_INTERNAL_OPT_SIZE")
	private String PRIMER_INTERNAL_OPT_SIZE;
	@JsonProperty("PRIMER_INTERNAL_MAX_SIZE")
	private String PRIMER_INTERNAL_MAX_SIZE;
	@JsonProperty("PRIMER_INTERNAL_MIN_TM")
	private String PRIMER_INTERNAL_MIN_TM;
	@JsonProperty("PRIMER_INTERNAL_OPT_TM")
	private String PRIMER_INTERNAL_OPT_TM;
	@JsonProperty("PRIMER_INTERNAL_MAX_TM")
	private String PRIMER_INTERNAL_MAX_TM;
	@JsonProperty("PRIMER_INTERNAL_MIN_GC")
	private String PRIMER_INTERNAL_MIN_GC;
	@JsonProperty("PRIMER_INTERNAL_OPT_GC_PERCENT")
	private String PRIMER_INTERNAL_OPT_GC_PERCENT;
	@JsonProperty("PRIMER_INTERNAL_MAX_GC")
	private String PRIMER_INTERNAL_MAX_GC;
	@JsonProperty("PRIMER_INTERNAL_MIN_TM_VAR")
	private String PRIMER_INTERNAL_MIN_TM_VAR;
	@JsonProperty("PRIMER_INTERNAL_TERMINAL_EXCLUDED_VAR")
	private String PRIMER_INTERNAL_TERMINAL_EXCLUDED_VAR;
	@JsonProperty("PRIMER_INTERNAL_MOD_NEAR_VAR")
	private String PRIMER_INTERNAL_MOD_NEAR_VAR;
	@JsonProperty("PRIMER_INTERNAL_MOD_VAR_DISTANCE")
	private String PRIMER_INTERNAL_MOD_VAR_DISTANCE;
	@JsonProperty("PRIMER_INTERNAL_MAX_LIBRARY_MISHYB")
	private String PRIMER_INTERNAL_MAX_LIBRARY_MISHYB;
	@JsonProperty("PRIMER_INTERNAL_MAX_TEMPLATE_MISHYB_TH")
	private String PRIMER_INTERNAL_MAX_TEMPLATE_MISHYB_TH;
	@JsonProperty("PRIMER_INTERNAL_MAX_SELF_ANY_TH")
	private String PRIMER_INTERNAL_MAX_SELF_ANY_TH;
	@JsonProperty("PRIMER_INTERNAL_MAX_SELF_END_TH")
	private String PRIMER_INTERNAL_MAX_SELF_END_TH;
	@JsonProperty("PRIMER_INTERNAL_MAX_TEMPLATE_MISHYB")
	private String PRIMER_INTERNAL_MAX_TEMPLATE_MISHYB;
	@JsonProperty("PRIMER_INTERNAL_MAX_SELF_ANY")
	private String PRIMER_INTERNAL_MAX_SELF_ANY;
	@JsonProperty("PRIMER_INTERNAL_MAX_SELF_END")
	private String PRIMER_INTERNAL_MAX_SELF_END;
	@JsonProperty("PRIMER_INTERNAL_MAX_HAIRPIN_TH")
	private String PRIMER_INTERNAL_MAX_HAIRPIN_TH;
	@JsonProperty("PRIMER_INTERNAL_MAX_NS_ACCEPTED")
	private String PRIMER_INTERNAL_MAX_NS_ACCEPTED;
	@JsonProperty("PRIMER_INTERNAL_MAX_POLY_X")
	private String PRIMER_INTERNAL_MAX_POLY_X;
	@JsonProperty("PRIMER_INTERNAL_DNA_CONC")
	private String PRIMER_INTERNAL_DNA_CONC;
	@JsonProperty("PRIMER_INTERNAL_5_PRIME_TERMINAL_EXCLUDED_MOD")
	private String PRIMER_INTERNAL_5_PRIME_TERMINAL_EXCLUDED_MOD;
	@JsonProperty("PRIMER_INTERNAL_3_PRIME_TERMINAL_EXCLUDED_MOD")
	private String PRIMER_INTERNAL_3_PRIME_TERMINAL_EXCLUDED_MOD;
	@JsonProperty("PRIMER_TM_FORMULA")
	private String PRIMER_TM_FORMULA;
	@JsonProperty("PRIMER_SALT_CORRECTIONS")
	private String PRIMER_SALT_CORRECTIONS;
	@JsonProperty("PRIMER_SALT_MONOVALENT")
	private String PRIMER_SALT_MONOVALENT;
	@JsonProperty("PRIMER_SALT_DIVALENT")
	private String PRIMER_SALT_DIVALENT;
	@JsonProperty("PRIMER_DNTP_CONC")
	private String PRIMER_DNTP_CONC;
	@JsonProperty("MUST_XLATE_PRIMER_LIBERAL_BASE")
	private String MUST_XLATE_PRIMER_LIBERAL_BASE;
	@JsonProperty("MUST_XLATE_PRIMER_PICK_ANYWAY")
	private String MUST_XLATE_PRIMER_PICK_ANYWAY;
	@JsonProperty("MUST_XLATE_PRIMER_EXPLAIN_FLAG")
	private String MUST_XLATE_PRIMER_EXPLAIN_FLAG;
	@JsonProperty("PRIMER_WT_SIZE_LT")
	private String PRIMER_WT_SIZE_LT;
	@JsonProperty("PRIMER_WT_SIZE_GT")
	private String PRIMER_WT_SIZE_GT;
	@JsonProperty("PRIMER_WT_TM_LT")
	private String PRIMER_WT_TM_LT;
	@JsonProperty("PRIMER_WT_TM_GT")
	private String PRIMER_WT_TM_GT;
	@JsonProperty("PRIMER_WT_GC_PERCENT_LT")
	private String PRIMER_WT_GC_PERCENT_LT;
	@JsonProperty("PRIMER_WT_GC_PERCENT_GT")
	private String PRIMER_WT_GC_PERCENT_GT;
	@JsonProperty("PRIMER_WT_SELF_ANY_TH")
	private String PRIMER_WT_SELF_ANY_TH;
	@JsonProperty("PRIMER_WT_SELF_END_TH")
	private String PRIMER_WT_SELF_END_TH;
	@JsonProperty("PRIMER_WT_TEMPLATE_MISPRIMING_TH")
	private String PRIMER_WT_TEMPLATE_MISPRIMING_TH;
	@JsonProperty("PRIMER_WT_SELF_ANY")
	private String PRIMER_WT_SELF_ANY;
	@JsonProperty("PRIMER_WT_SELF_END")
	private String PRIMER_WT_SELF_END;
	@JsonProperty("PRIMER_WT_TEMPLATE_MISPRIMING")
	private String PRIMER_WT_TEMPLATE_MISPRIMING;
	@JsonProperty("PRIMER_WT_HAIRPIN_TH")
	private String PRIMER_WT_HAIRPIN_TH;
	@JsonProperty("PRIMER_WT_NUM_NS")
	private String PRIMER_WT_NUM_NS;
	@JsonProperty("PRIMER_WT_LIBRARY_MISPRIMING")
	private String PRIMER_WT_LIBRARY_MISPRIMING;
	@JsonProperty("PRIMER_WT_POS_PENALTY")
	private String PRIMER_WT_POS_PENALTY;
	@JsonProperty("PRIMER_WT_END_STABILITY")
	private String PRIMER_WT_END_STABILITY;
	@JsonProperty("PRIMER_PAIR_WT_PRODUCT_SIZE_LT")
	private String PRIMER_PAIR_WT_PRODUCT_SIZE_LT;
	@JsonProperty("PRIMER_PAIR_WT_PRODUCT_SIZE_GT")
	private String PRIMER_PAIR_WT_PRODUCT_SIZE_GT;
	@JsonProperty("PRIMER_PAIR_WT_PRODUCT_TM_LT")
	private String PRIMER_PAIR_WT_PRODUCT_TM_LT;
	@JsonProperty("PRIMER_PAIR_WT_PRODUCT_TM_GT")
	private String PRIMER_PAIR_WT_PRODUCT_TM_GT;
	@JsonProperty("PRIMER_PAIR_WT_COMPL_ANY_TH")
	private String PRIMER_PAIR_WT_COMPL_ANY_TH;
	@JsonProperty("PRIMER_PAIR_WT_COMPL_END_TH")
	private String PRIMER_PAIR_WT_COMPL_END_TH;
	@JsonProperty("PRIMER_PAIR_WT_TEMPLATE_MISPRIMING_TH")
	private String PRIMER_PAIR_WT_TEMPLATE_MISPRIMING_TH;
	@JsonProperty("PRIMER_PAIR_WT_COMPL_ANY")
	private String PRIMER_PAIR_WT_COMPL_ANY;
	@JsonProperty("PRIMER_PAIR_WT_COMPL_END")
	private String PRIMER_PAIR_WT_COMPL_END;
	@JsonProperty("PRIMER_PAIR_WT_TEMPLATE_MISPRIMING")
	private String PRIMER_PAIR_WT_TEMPLATE_MISPRIMING;
	@JsonProperty("PRIMER_PAIR_WT_DIFF_TM")
	private String PRIMER_PAIR_WT_DIFF_TM;
	@JsonProperty("PRIMER_PAIR_WT_LIBRARY_MISPRIMING")
	private String PRIMER_PAIR_WT_LIBRARY_MISPRIMING;
	@JsonProperty("PRIMER_PAIR_WT_PR_PENALTY")
	private String PRIMER_PAIR_WT_PR_PENALTY;
	@JsonProperty("PRIMER_PAIR_WT_IO_PENALTY")
	private String PRIMER_PAIR_WT_IO_PENALTY;
	@JsonProperty("PRIMER_INTERNAL_WT_SIZE_LT")
	private String PRIMER_INTERNAL_WT_SIZE_LT;
	@JsonProperty("PRIMER_INTERNAL_WT_SIZE_GT")
	private String PRIMER_INTERNAL_WT_SIZE_GT;
	@JsonProperty("PRIMER_INTERNAL_WT_TM_LT")
	private String PRIMER_INTERNAL_WT_TM_LT;
	@JsonProperty("PRIMER_INTERNAL_WT_TM_GT")
	private String PRIMER_INTERNAL_WT_TM_GT;
	@JsonProperty("PRIMER_INTERNAL_WT_GC_PERCENT_LT")
	private String PRIMER_INTERNAL_WT_GC_PERCENT_LT;
	@JsonProperty("PRIMER_INTERNAL_WT_GC_PERCENT_GT")
	private String PRIMER_INTERNAL_WT_GC_PERCENT_GT;
	@JsonProperty("PRIMER_INTERNAL_WT_DIFF_TM_VAR")
	private String PRIMER_INTERNAL_WT_DIFF_TM_VAR;
	@JsonProperty("PRIMER_INTERNAL_WT_SELF_ANY_TH")
	private String PRIMER_INTERNAL_WT_SELF_ANY_TH;
	@JsonProperty("PRIMER_INTERNAL_WT_SELF_END_TH")
	private String PRIMER_INTERNAL_WT_SELF_END_TH;
	@JsonProperty("PRIMER_INTERNAL_WT_TEMPLATE_MISHYB_TH")
	private String PRIMER_INTERNAL_WT_TEMPLATE_MISHYB_TH;
	@JsonProperty("PRIMER_INTERNAL_WT_SELF_ANY")
	private String PRIMER_INTERNAL_WT_SELF_ANY;
	@JsonProperty("PRIMER_INTERNAL_WT_SELF_END")
	private String PRIMER_INTERNAL_WT_SELF_END;
	@JsonProperty("PRIMER_INTERNAL_WT_TEMPLATE_MISHYB")
	private String PRIMER_INTERNAL_WT_TEMPLATE_MISHYB;
	@JsonProperty("PRIMER_INTERNAL_WT_HAIRPIN_TH")
	private String PRIMER_INTERNAL_WT_HAIRPIN_TH;
	@JsonProperty("PRIMER_INTERNAL_WT_NUM_NS")
	private String PRIMER_INTERNAL_WT_NUM_NS;
	@JsonProperty("PRIMER_INTERNAL_WT_LIBRARY_MISHYB")
	private String PRIMER_INTERNAL_WT_LIBRARY_MISHYB;
	@JsonProperty("PRIMER_INTERNAL_WT_MOD_POS")
	private String PRIMER_INTERNAL_WT_MOD_POS;
	@JsonProperty("SEQUENCE_START_CODON_POSITION")
	private String SEQUENCE_START_CODON_POSITION;
	@JsonProperty("SEQUENCE_QUALITY")
	private String SEQUENCE_QUALITY;
	@JsonProperty("PRIMER_MIN_QUALITY")
	private String PRIMER_MIN_QUALITY;
	@JsonProperty("PRIMER_MIN_END_QUALITY")
	private String PRIMER_MIN_END_QUALITY;
	@JsonProperty("PRIMER_QUALITY_RANGE_MIN")
	private String PRIMER_QUALITY_RANGE_MIN;
	@JsonProperty("PRIMER_QUALITY_RANGE_MAX")
	private String PRIMER_QUALITY_RANGE_MAX;
	@JsonProperty("PRIMER_SEQUENCING_SPACING")
	private String PRIMER_SEQUENCING_SPACING;
	@JsonProperty("PRIMER_SEQUENCING_INTERVAL")
	private String PRIMER_SEQUENCING_INTERVAL;
	@JsonProperty("PRIMER_SEQUENCING_LEAD")
	private String PRIMER_SEQUENCING_LEAD;
	@JsonProperty("PRIMER_SEQUENCING_ACCURACY")
	private String PRIMER_SEQUENCING_ACCURACY;
	@JsonProperty("PRIMER_INTERNAL_MIN_QUALITY")
	private String PRIMER_INTERNAL_MIN_QUALITY;
	@JsonProperty("PRIMER_INTERNAL_MISHYB_LIBRARY")
	private String PRIMER_INTERNAL_MISHYB_LIBRARY;
	@JsonProperty("PRIMER_INTERNAL_SALT_MONOVALENT")
	private String PRIMER_INTERNAL_SALT_MONOVALENT;
	@JsonProperty("PRIMER_INTERNAL_SALT_DIVALENT")
	private String PRIMER_INTERNAL_SALT_DIVALENT;
	@JsonProperty("PRIMER_INTERNAL_DNTP_CONC")
	private String PRIMER_INTERNAL_DNTP_CONC;
	@JsonProperty("PRIMER_TASK")
	private String PRIMER_TASK;

}
